# -*- coding: utf-8 -*-
"""DATA543_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvSPkYVMVig1jwLCbLWcuqT7VYTwCvQv
"""

# installs and imports
!pip install pandas numpy scikit-learn matplotlib seaborn imbalanced-learn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    roc_auc_score, roc_curve, mean_squared_error, r2_score
)
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')
print("Imports done")

# load files
# Upload breach_report.csv and known_exploited_vulnerabilities.csv
# via the Colab Files panel (📁 icon). Then run this cell.

# CISA KEV
kev_df = pd.read_csv("known_exploited_vulnerabilities.csv")
# Columns: cveID, vendorProject, product, vulnerabilityName, dateAdded,
#          shortDescription, requiredAction, dueDate,
#          knownRansomwareCampaignUse, notes, cwes
print(f"KEV loaded: {len(kev_df)} vulnerabilities")

# HHS OCR Breach Report
breach_df = pd.read_csv("breach_report.csv")
# Raw export has JSF component names as column headers — rename them cleanly:
breach_df.columns = [
    'Entity_Name', 'State', 'Covered_Entity_Type', 'Individuals_Affected',
    'Breach_Submission_Date', 'Type_of_Breach', 'Location_of_Breach',
    'Business_Associate_Present', 'Web_Description'
]
print(f"Breach report loaded: {len(breach_df)} incidents")

# feature engineering - build a breach-level feature matrix (each row = one reported breach), target: is this a "high-impact" breach (high-risk = 1)?

# clean breach data
breach = breach_df.copy()
breach['Individuals_Affected'] = pd.to_numeric(
    breach['Individuals_Affected'], errors='coerce'
).fillna(0)
breach['Breach_Submission_Date'] = pd.to_datetime(
    breach['Breach_Submission_Date'], errors='coerce'
)
breach['Year'] = breach['Breach_Submission_Date'].dt.year.fillna(2023).astype(int)
breach['State'] = breach['State'].fillna('Unknown')

# hazard features from KEV - count vulnerabilities added per year as a proxy for annual threat level
kev_df['dateAdded'] = pd.to_datetime(kev_df['dateAdded'], errors='coerce')
kev_df['year'] = kev_df['dateAdded'].dt.year
kev_annual = kev_df.groupby('year').size().rename('kev_count_that_year')
kev_ransomware = kev_df[kev_df['knownRansomwareCampaignUse'] == 'Known'] \
    .groupby('year').size().rename('ransomware_kev_count')

breach = breach.merge(
    kev_annual.reset_index().rename(columns={'year': 'Year'}),
    on='Year', how='left'
).merge(
    kev_ransomware.reset_index().rename(columns={'year': 'Year'}),
    on='Year', how='left'
)
breach['kev_count_that_year'] = breach['kev_count_that_year'].fillna(0)
breach['ransomware_kev_count'] = breach['ransomware_kev_count'].fillna(0)

# exposure features - state-level breach density (how many breaches has this state had?)
state_breach_count = breach.groupby('State').size().rename('state_breach_count')
breach = breach.merge(state_breach_count.reset_index(), on='State', how='left')

# state total individuals affected (cumulative exposure by state)
state_individuals = breach.groupby('State')['Individuals_Affected'] \
    .sum().rename('state_total_individuals')
breach = breach.merge(state_individuals.reset_index(), on='State', how='left')

# vulnerability features - is the breach a hacking/IT incident? (highest severity type)
breach['is_hacking'] = (
    breach['Type_of_Breach'].str.contains('Hacking', case=False, na=False)
).astype(int)

# find out if a network server is involved (OT/network exposure proxy)
breach['is_network_server'] = (
    breach['Location_of_Breach'].str.contains('Network Server', case=False, na=False)
).astype(int)

# is a business associate involved? (third-party/supply chain risk)
breach['has_business_associate'] = (
    breach['Business_Associate_Present'].str.upper() == 'YES'
).astype(int)

# entity type dummies
entity_dummies = pd.get_dummies(
    breach['Covered_Entity_Type'], prefix='entity', drop_first=True
)

# define target 
# high risk = breach is in top quartile of individuals affected
#             AND is a hacking/IT incident (the most dangerous combo)
high_impact_threshold = breach['Individuals_Affected'].quantile(0.75)
breach['high_risk'] = (
    (breach['Individuals_Affected'] >= high_impact_threshold) &
    (breach['is_hacking'] == 1)
).astype(int)

print(f"High-risk breaches: {breach['high_risk'].sum()} / {len(breach)} "
      f"({breach['high_risk'].mean():.1%})")
print(f"Threshold (75th pct): {high_impact_threshold:,.0f} individuals affected")

# final feature matrix
FEATURE_COLS = [
    'kev_count_that_year',       # HAZARD: active exploits in that year
    'ransomware_kev_count',      # HAZARD: ransomware-linked exploits
    'state_breach_count',        # EXPOSURE: how breach-heavy is this state
    'state_total_individuals',   # EXPOSURE: cumulative impact in state
    'is_hacking',                # VULNERABILITY: attack type
    'is_network_server',         # VULNERABILITY: attack surface
    'has_business_associate',    # VULNERABILITY: supply chain risk
    'Year',                      # TEMPORAL: trend over time
]

X_raw = pd.concat([
    breach[FEATURE_COLS].reset_index(drop=True),
    entity_dummies.reset_index(drop=True)
], axis=1)
y = breach['high_risk'].values

print(f"\nFeature matrix shape: {X_raw.shape}")
print("Features:", X_raw.columns.tolist())

# EDA
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle('DATA543 — Exploratory Data Analysis', fontsize=14, fontweight='bold')

# 1. Breach type distribution
breach['Type_of_Breach'].value_counts().plot(
    kind='bar', ax=axes[0,0], color='steelblue', edgecolor='k'
)
axes[0,0].set_title('Breach Type Distribution')
axes[0,0].set_xlabel('')
axes[0,0].tick_params(axis='x', rotation=30)

# 2. High-risk vs low-risk breakdown
breach['high_risk'].value_counts().rename(
    {0: 'Low Risk', 1: 'High Risk'}
).plot(kind='bar', ax=axes[0,1], color=['seagreen', 'tomato'], edgecolor='k')
axes[0,1].set_title('Risk Label Distribution')
axes[0,1].tick_params(axis='x', rotation=0)

# 3. Individuals affected (log scale)
axes[0,2].hist(
    np.log1p(breach['Individuals_Affected']), bins=40,
    color='steelblue', edgecolor='k'
)
axes[0,2].set_title('log(Individuals Affected)')
axes[0,2].set_xlabel('log1p(individuals)')

# 4. Top 15 states by breach count
top_states = breach['State'].value_counts().head(15)
top_states.plot(kind='bar', ax=axes[1,0], color='coral', edgecolor='k')
axes[1,0].set_title('Top 15 States by Breach Count')
axes[1,0].tick_params(axis='x', rotation=45)

# 5. KEV count over time
kev_annual_plot = kev_df.groupby('year').size()
axes[1,1].bar(kev_annual_plot.index, kev_annual_plot.values,
              color='mediumpurple', edgecolor='k')
axes[1,1].set_title('CISA KEV Entries Added Per Year')
axes[1,1].set_xlabel('Year')

# 6. Correlation heatmap
numeric_cols = FEATURE_COLS + ['high_risk']
corr = breach[numeric_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            ax=axes[1,2], cbar=True, linewidths=0.5)
axes[1,2].set_title('Feature Correlation Matrix')

plt.tight_layout()
plt.savefig('eda_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print("EDA complete")

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train: {X_train.shape[0]} rows | Test: {X_test.shape[0]} rows")
print(f"Train high-risk rate: {y_train.mean():.1%}")
print(f"Test  high-risk rate: {y_test.mean():.1%}")

# handle class imbalance with SMOTE
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)
print(f"\nAfter SMOTE — Train: {X_train_res.shape[0]} rows "
      f"(balanced {y_train_res.mean():.1%} high-risk)")

# Part A — Logistic Regression Classifier
print("=" * 60)
print("PART A: CLASSIFICATION — Logistic Regression (L2)")
print("=" * 60)

# regularization sweep
print("\nRegularization sweep (5-fold CV, AUC):")
for C_val in [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]:
    pipe = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',  StandardScaler()),
        ('clf',     LogisticRegression(C=C_val, penalty='l2',
                                       max_iter=2000, random_state=42))
    ])
    cv_scores = cross_val_score(
        pipe, X_train_res, y_train_res,
        cv=StratifiedKFold(5, shuffle=True, random_state=42),
        scoring='roc_auc'
    )
    print(f"  C={C_val:<8} AUC: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

# best model (C=1.0 — tune based on sweep output above)
best_C = 1.0
clf_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler',  StandardScaler()),
    ('clf',     LogisticRegression(C=best_C, penalty='l2',
                                   max_iter=2000, random_state=42))
])
clf_pipe.fit(X_train_res, y_train_res)
y_pred  = clf_pipe.predict(X_test)
y_proba = clf_pipe.predict_proba(X_test)[:, 1]

print(f"\n── Final Model (C={best_C}) on Test Set ──────────────────────────")
print(classification_report(y_test, y_pred, target_names=['Low Risk','High Risk']))
print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.3f}")

# plots
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Part A: Logistic Regression Results', fontsize=13, fontweight='bold')

# confusion matrix
ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred,
    display_labels=['Low Risk', 'High Risk'],
    cmap='Blues', ax=axes[0]
)
axes[0].set_title('Confusion Matrix')

# ROC curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, lw=2.5, color='steelblue',
             label=f'AUC = {roc_auc_score(y_test, y_proba):.3f}')
axes[1].plot([0,1],[0,1],'k--', lw=1)
axes[1].fill_between(fpr, tpr, alpha=0.1, color='steelblue')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].set_title('ROC Curve')
axes[1].legend()

# feature coefficients
feature_names = X_raw.columns.tolist()
coefs = clf_pipe.named_steps['clf'].coef_[0]
coef_df = pd.DataFrame({'feature': feature_names, 'coefficient': coefs}) \
            .sort_values('coefficient', key=abs, ascending=True)
colors = ['tomato' if c > 0 else 'steelblue' for c in coef_df['coefficient']]
axes[2].barh(coef_df['feature'], coef_df['coefficient'], color=colors, edgecolor='k')
axes[2].axvline(0, color='k', lw=0.8)
axes[2].set_title('L2 Coefficients\n(red=risk-increasing, blue=risk-reducing)')

plt.tight_layout()
plt.savefig('classification_results.png', dpi=150, bbox_inches='tight')
plt.show()

# Part B — Regression (Continuous Risk Score)
print("=" * 60)
print("PART B: REGRESSION — Continuous Risk Score")
print("=" * 60)

# target: log of individuals affected (continuous severity measure)
y_reg = np.log1p(breach['Individuals_Affected'].values)

X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_raw, y_reg, test_size=0.2, random_state=42
)

# Compare OLS, Ridge (L2), Lasso (L1)
reg_results = {}
models = {
    'OLS (no reg)':  Pipeline([('imp', SimpleImputer(strategy='median')),
                                ('scl', StandardScaler()),
                                ('reg', Ridge(alpha=0.001))]),
    'Ridge (L2)':    Pipeline([('imp', SimpleImputer(strategy='median')),
                                ('scl', StandardScaler()),
                                ('reg', Ridge(alpha=1.0))]),
    'Lasso (L1)':    Pipeline([('imp', SimpleImputer(strategy='median')),
                                ('scl', StandardScaler()),
                                ('reg', Lasso(alpha=0.05, max_iter=10000))]),
}

print(f"\n{'Model':<20} {'RMSE':>8} {'R²':>8}  CV-R² (5-fold)")
for name, model in models.items():
    model.fit(X_reg_train, y_reg_train)
    preds = model.predict(X_reg_test)
    rmse = np.sqrt(mean_squared_error(y_reg_test, preds))
    r2   = r2_score(y_reg_test, preds)
    cv   = cross_val_score(model, X_reg_train, y_reg_train,
                           cv=5, scoring='r2').mean()
    reg_results[name] = {'rmse': rmse, 'r2': r2, 'cv_r2': cv,
                         'model': model, 'preds': preds}
    print(f"{name:<20} {rmse:>8.3f} {r2:>8.3f}  {cv:.3f}")

best_reg_name = max(reg_results, key=lambda k: reg_results[k]['r2'])
best_preds = reg_results[best_reg_name]['preds']
print(f"\nBest model: {best_reg_name}")

# Plots
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Part B: Regression Results', fontsize=13, fontweight='bold')

# Predicted vs Actual
axes[0].scatter(y_reg_test, best_preds, alpha=0.4, s=20, color='steelblue')
lims = [min(y_reg_test.min(), best_preds.min()),
        max(y_reg_test.max(), best_preds.max())]
axes[0].plot(lims, lims, 'r--', lw=1.5)
axes[0].set_xlabel('Actual log(Individuals Affected)')
axes[0].set_ylabel('Predicted')
axes[0].set_title(f'Predicted vs Actual\n({best_reg_name})')

# Residuals
residuals = y_reg_test - best_preds
axes[1].hist(residuals, bins=35, color='steelblue', edgecolor='k')
axes[1].axvline(0, color='r', lw=1.5)
axes[1].set_xlabel('Residual')
axes[1].set_title('Residual Distribution')

# Regression coefficients
best_model_obj = reg_results[best_reg_name]['model']
reg_coefs = best_model_obj.named_steps['reg'].coef_
reg_coef_df = pd.DataFrame({
    'feature': X_raw.columns,
    'coefficient': reg_coefs
}).sort_values('coefficient', key=abs, ascending=True)
colors_reg = ['tomato' if c > 0 else 'steelblue' for c in reg_coef_df['coefficient']]
axes[2].barh(reg_coef_df['feature'], reg_coef_df['coefficient'],
             color=colors_reg, edgecolor='k')
axes[2].axvline(0, color='k', lw=0.8)
axes[2].set_title(f'Regression Coefficients\n({best_reg_name})')

plt.tight_layout()
plt.savefig('regression_results.png', dpi=150, bbox_inches='tight')
plt.show()

# Deliverable — Risk Rankings 
print("=" * 60)
print("DELIVERABLES: Risk Rankings")
print("=" * 60)

# Add predicted risk score back to breach dataframe
breach_scored = breach.copy()
breach_scored['predicted_log_severity'] = reg_results[best_reg_name]['model'].predict(X_raw)
breach_scored['predicted_severity'] = np.expm1(breach_scored['predicted_log_severity'])

# Ranking 1: By entity type 
entity_risk = breach_scored.groupby('Covered_Entity_Type').agg(
    breach_count=('high_risk', 'count'),
    high_risk_rate=('high_risk', 'mean'),
    avg_individuals_affected=('Individuals_Affected', 'mean'),
    avg_predicted_severity=('predicted_severity', 'mean')
).sort_values('high_risk_rate', ascending=False).round(2)

print("\n── Risk Ranking by Entity Type ─────────────────────────────────")
print(entity_risk.to_string())

# Ranking 2: Geographic (top 20 states) 
state_risk = breach_scored.groupby('State').agg(
    breach_count=('Entity_Name', 'count'),
    high_risk_count=('high_risk', 'sum'),
    high_risk_rate=('high_risk', 'mean'),
    total_individuals=('Individuals_Affected', 'sum'),
    avg_predicted_severity=('predicted_severity', 'mean')
).sort_values('avg_predicted_severity', ascending=False).round(2)

print("\n── Top 20 States by Predicted Severity ──────────────────────────")
print(state_risk.head(20).to_string())

# Ranking 3: Breach type risk profile 
type_risk = breach_scored.groupby('Type_of_Breach').agg(
    count=('high_risk', 'count'),
    high_risk_rate=('high_risk', 'mean'),
    avg_individuals=('Individuals_Affected', 'mean')
).sort_values('high_risk_rate', ascending=False).round(2)

print("\n── Risk by Breach Type ───────────────────────────────────────────")
print(type_risk.to_string())

# Final summary plot
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('DATA543 — Risk Rankings Summary', fontsize=13, fontweight='bold')

# State risk bar chart (top 20)
top20 = state_risk.head(20)
axes[0].barh(top20.index[::-1], top20['avg_predicted_severity'][::-1],
             color='tomato', edgecolor='k')
axes[0].set_title('Top 20 States\n(Avg Predicted Breach Severity)')
axes[0].set_xlabel('Predicted Individuals Affected')

# Entity type risk
entity_risk['high_risk_rate'].sort_values().plot(
    kind='barh', ax=axes[1], color='mediumpurple', edgecolor='k'
)
axes[1].set_title('High-Risk Rate by Entity Type')
axes[1].set_xlabel('Proportion of Breaches Classified High-Risk')

plt.tight_layout()
plt.savefig('risk_rankings.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ All cells complete. Saved plots: eda_plots.png, "
      "classification_results.png, regression_results.png, risk_rankings.png")
